---
title: "Ecoystem Based Model"
author: "Abigail Grassick"
date: "12/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("Functions_Rscript.R")
library(ggplot2)
library(tidyverse)
```

## Ecosystem Based Model

##Creating the functions based on Mumby et al 2007 (Nature)
```{r}
#dMdt=macroalgal growth rate
#parameters:
#a=growth rate of algae over coral
#M= Macroalgae cover
#C= Coral cover
#g= grazing rate of macro and turf over time
#T_= Turf cover
#y= growth rate of macro over turf
#C+M+T= 1 (total coverage in the system)
F_dMdt <- function(a, M, C, g, T_, y){
  dMdt <- (a*M*C)-((g*(M/(M+T_))))+(y*M*T_)
  return(dMdt)
}

#dCdt= coral growth rate
#parameters:
#a=growth rate of algae over coral
#M= Macroalgae cover
#C= Coral cover
#T_= Turf cover
#r=growth rate of coral over turf
#d= natural coral mortality 
F_dCdt <- function(r,T_, C, d, a, M){
  dCdt <- (r*T_*C)-(d*C)-(a*M*C)
  return(dCdt)
}

```

#loop to simulate our functions 
```{r}
#test simulation
#define our parameters
a <- 0.936
r<- .208
d <- .035
y<- -.0012
M<- .3
C<- .25
T_<- 1-M-C
g<- .1
dt<- .01

v_M_values1 <- vector(length=10/dt)
v_M_values1[1] <- M 
v_C_values1 <- vector(length=10/dt)
v_C_values1[1]<- C

for(index_time in 2:length(v_M_values1)){
  current_M_value <- v_M_values1[index_time-1]
  current_C_value <- v_C_values1[index_time-1]
  v_M_values1[index_time] <- current_M_value+(dt*F_dMdt(a,M,C,g,T_,y))
  v_C_values1[index_time] <- current_C_value+ (dt*F_dCdt(r,T_,C,d,a,M))
  M <- current_M_value
  C <- current_C_value
  T_<- 1-M-C
}


M<- .4
C<- .1
v_M_values2 <- vector(length=10/dt)
v_M_values2[1] <- M 
v_C_values2 <- vector(length=10/dt)
v_C_values2[1]<- C

for(index_time2 in 2:length(v_M_values2)){
  current_M_value <- v_M_values2[index_time2-1]
  current_C_value <- v_C_values2[index_time2-1]
  v_M_values2[index_time2] <- current_M_value+(dt*F_dMdt(a,M,C,g,T_,y))
  v_C_values2[index_time2] <- current_C_value+ (dt*F_dCdt(r,T_,C,d,a,M))
  M <- current_M_value
  C <- current_C_value
  T_<- 1-M-C
}

M<- .1
C<- .6
v_M_values3 <- vector(length=10/dt)
v_M_values3[1] <- M 
v_C_values3 <- vector(length=10/dt)
v_C_values3[1]<- C

for(index_time3 in 2:length(v_M_values3)){
  current_M_value <- v_M_values3[index_time3-1]
  current_C_value <- v_C_values3[index_time3-1]
  v_M_values3[index_time3] <- current_M_value+(dt*F_dMdt(a,M,C,g,T_,y))
  v_C_values3[index_time3] <- current_C_value+ (dt*F_dCdt(r,T_,C,d,a,M))
  M <- current_M_value
  C <- current_C_value
  T_<- 1-M-C
}

data.frame(v_M_values1,v_C_values1,v_M_values2, v_C_values2,v_M_values3, v_C_values3 )

ggplot(data=points_test)+
  geom_point(aes(x=v_M_values1, y=v_C_values1, color="v_M_values1"))+
   geom_point(aes(x=v_M_values2, y=v_C_values2, color="v_M_values2"))+
   geom_point(aes(x=v_M_values3, y=v_C_values3, color="v_M_values3"))

```
#now we can begin to iterate different grazing rates through our functions to determine 
```{r}
#define parameters that are not called with the function
a <- 0.2
r<- 0.1
d <-0.035
y<- 0.5
dt<- .01

#generate 1 series
generate_series <- function(C, M, g){
  v_M_values1 <- vector()
  v_C_values1 <- vector()
  v_M_values1[1] <-M 
  v_C_values1[1]<- C
  T_<- 1-M-C
  index_time=2
  delta_M <-1
  delta_C <-1
  while(sqrt(delta_M^2+delta_C^2) >.00000001){
    M <- v_M_values1[index_time-1]
    C <- v_C_values1[index_time-1]
    T_<- 1-M-C
    newM<- M+(dt*F_dMdt(a,M,C,g,T_,y))
    newC <- C+ (dt*F_dCdt(r,T_,C,d,a,M))
    v_M_values1[index_time] <- newM
    v_C_values1[index_time]<- newC
    delta_M<- newM-M
    delta_C<- newC-C
    index_time<- index_time+1
  }
  single_series_df <- data.frame(v_M_values1,v_C_values1)
  return(single_series_df)
}
#test to see if it works (it does)
generate_series(.2,.2, .1)

#function to test different start values
list_M_values<- seq(0,1,by=.05)
list_C_values <- seq(0,1,by=.05)
paired_values<-expand.grid(list_M_values,list_C_values)
#subset the data so that M+C<1 so that we dont run the function for unfeasible values (T+M+C=1)
paired_values<-subset(paired_values, Var1+Var2<1)
  
f_start_values <- function(g){
  for(index_start in 1:nrow(paired_values) ){
    M<- paired_values[index_start,1]
    C<- paired_values[index_start,2]
    stored_values<-generate_series(C,M,g)
    paired_values$Mfinal[index_start]<- stored_values[nrow(stored_values),1]
    paired_values$Cfinal[index_start]<- stored_values[nrow(stored_values),2]
  }
  return(paired_values)
}

paired_values$coral_state<- if(paired_values$Mfinal<.01){TRUE}else{FALSE}

  
sample_end_traj<-f_start_values(.1)
sample_end_traj_2states <- f_start_values(.3)
#plot sample end states of trajectories 
test.plot<-ggplot()+
  geom_point(data=sample_end_traj, aes(x=Mfinal, y=Cfinal,color="g=.1"))+
  geom_point(data=sample_end_traj_2states, aes(x=Mfinal, y=Cfinal, color="g=.3"))
test.plot

```


```{r}
#for loop to test all possible g values to determine stable states; we sequenced up to .3 because this is the lowest value we know a dual stable state to exist at (Mumby et al 2007)
gtest<- seq(.2,.3, by=.005)
grazing_df <- data.frame()

l_simulated_data<-vector(mode="list")

for(index_g in 1:length(gtest)){
  g<- gtest[index_g]
  start_values<-f_start_values(g)
  start_values$g <- g
  l_simulated_data[[index_g]]<- start_values
 
}

simulated_g_data <- do.call(rbind,l_simulated_data)
#this saves the data from the above loop into a data library 
save(simulated_g_data, file="model_g_trajectories.Rdata")

#simulated_g_data$coral_state<- if(simulated_g_data[,3]<0.01){TRUE}else{FALSE}
simulated_g_data<-mutate(simulated_g_data,coral_state=(Mfinal<0.01))
save(simulated_g_data, file="model_g_trajectories.Rdata")


plot_end_trajectories<-ggplot(data=simulated_g_data, aes(x=Mfinal, y=Cfinal, color=as.factor(g)))+
  geom_point(alpha=.5)+
  labs(title="End Trajectories of all G values", x="Macro Algal Coverage", y="Coral Coverage", color="Grazing Rate")+
theme_bw()

ggplot(data=simulated_g_data, aes(x=Mfinal, y=Cfinal, color=as.factor(g)), group=coral_state)+
  geom_point(alpha=.5)+
  labs(title="End Trajectories of all G values", x="Macro Algal Coverage", y="Coral Coverage", color="Grazing Rate")+
theme_bw()

plot_end_trajectories
```

```{r}
ggplot(data=simulated_g_data,aes(x=g, fill=coral_state))+
  geom_bar()+
  labs(title="Proportion of starting conditions which result in coral stable states by grazing value", x="Grazing Rate", y="Proportion in Coral Stable State", fill="Coral Stable State")+
theme_bw()

ggplot(data=simulated_g_data, aes(x=g, y=))

```

