---
title: "Workflow and functions"
author: "Abigail Grassick"
date: "12/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Work flow
Ecosystem Based Model (Abby, Abigail)

##Problems we encountered notated by two hastags
#Functions notated by one hashtag


1. Create the function based on 
  Mumby et. al (Nature, 2007)
#    F_dMdt (macroalgal growth rate function) and 
#    F_dCdt (coral growth rate)
  
2. Create for Loop to simulate the function, conducting a test first

  -define the parameters using 
    Mumby et. al (Nature, 2007)- T_, M, C  
    Vermeij et. al (2010)- r https://doi.org/10.1371/journal.pone.0014312 
    Mumby et al. (2006) - d, y
    Box, Mumby (2007)- a
    
##a, r, and y we later chose on our own. We based these on what we thought to be reasonable rates of growth for the system.    
    
  - use F_dMdt and F_dCdt functions to get outputs for each function at test values g=.1, M=.2, C=.2 and put them into vectors
    v_M_values
    v_C_values
    
  -Combine the two vectors into a data frame
    points_test
  
  -use ggplot to plot the test
##original test came out wrong. The coral values were returning as negative. 
  We adjusted the time step; that was not the issue. 
  Problem identified: we needed to combine the two for loops so M and C were being calculated   and replaced simultaneously. 
  
  -repeated this test 2 more times with values of M=.4 and C=.1 and vice versa, plotting all 3 to determine which stable state they are approaching at this  value of g
##the lines didnt seem to be approaching multiple stable states, so we had to reassses the parameter values. The issue we ran into was that the plot was     only approaching a macroalgae stable state. Our a value was high, so this made sense. We then found a value in the Box (2007) paper which helped us fix    the parameter value a.   

##The parameter values are still incorrect and not reflective of the ecosystem dynamics. We came up with some arbitrary values that make sense in terms of actual dynamics and used thos parameters instead. 
  
  
3. Iterating different grazing values through the for loop
  
  LOOP OF 3 LOOPS is needed to nest g iterations
  
  a. create a function that generates a single series of start values
#    generate_series
    
  -store the values in a data frame 
    single_series_df
  
  - use expand.grid() to order the C and M values as (x,y) pairs, not just linear progressions
    object: "paired values"
  
  -subset the paired values so that T+M+C<1
  
  b. create a function that loops through the start values for 1 value of g
#    f_start_values

  -save the tail end of the calculations into a data frame with the start values
   
  -plot the paired values data frame to see if the generated data is approaching two stable states
##This worked! Now, we want to test this with many values of g. 
  
  c. create a for loop to test different g values to determine the stable states 
    
  -g increases by intervals of .005 
  Mumby (Nature, 2007)
  
  -sequenced up to .3 because we know this is the lowest g value for the two stable states to exist
   Mumby (Nature, 2007)

  -Save the outputs into a single data frame by creating a list (l_simulated_data) and then binding the lists to a singular data frame (simulated_g_data).
  
4. Editing the generate_series function to be a while loop
  
  -we want to calculate delta M and delta C in order to gauge when the while loop should stop. This is the condition of the while loop. 
  
  -We then tested the loop to see what it was showing us. The loop gave us a better visual of the dynamics of the function. After plotting, this showed us the trajectories much clearer, so we know that the function has the ability to show us the different stable states. 
  
5. Run the model

  - The model worked!!
  
6. Organize and present the data 

  -We used tidyverse to add a column to our data frame. We added a true false statement where TRUE marks the end trajectories in a coral stable state and FALSE marks the end trajectories in a macroalgae stable state. 
  
  -Clean up the data;
    

  

Single Species Model (Kennady, Sabrina)
- determine the effects of biomass on grazing rate

Determination of Max sustained yeild based on grazing rate :) 

EDM
